# Generated by Django 2.0 on 2018-02-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HierarchyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartUsageHierarchyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.HierarchyName')),
            ],
        ),
        migrations.CreateModel(
            name='SearchValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='partusagehierarchyname',
            name='search_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.SearchValues'),
        ),
        migrations.AddField(
            model_name='hierarchyname',
            name='hierarchy_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.HierarchyValue'),
        ),
    ]
