# Generated by Django 2.0 on 2018-01-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_loader', '0003_output_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='search_type',
            field=models.CharField(choices=[(0, 'Text Search'), (1, 'Line Search'), (2, 'Paragraph Search')], default='Text Search', max_length=50),
        ),
    ]
