# Generated by Django 2.0 on 2018-01-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_loader', '0004_auto_20180127_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='search_type',
            field=models.CharField(choices=[('TEXT', 'Text Search'), ('LINE', 'Line Search'), ('PARAGRAPH', 'Paragraph Search')], default='Text Search', max_length=50),
        ),
    ]
