# Generated by Django 2.0 on 2018-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_loader', '0005_auto_20180127_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='search_type',
            field=models.CharField(choices=[('TEXT', 'Text Search'), ('LINE', 'Line Search'), ('PARAGRAPH', 'Paragraph Search')], default='TEXT', max_length=50),
        ),
    ]
